// This file was automatically generated using tools/process_csv.py
// Generated on Thu Jul 02 2020 23:45:53 UTC

#pragma once

#include <Zenova/Hook.h>

extern "C" {
	extern void* _getPacks_VanillaInPackagePacks__QEBA_AV_$vector_UMetaData_IInPackagePacks__V_$allocator_UMetaData_IInPackagePacks___std___std__W4PackType___Z_ptr;
	extern void* _initializeBehaviorStack_VanillaGameModuleServer__QEAAXAEBVGameRules__AEAVResourcePackRepository__AEAVResourcePackStack__AEBVBaseGameVersion___Z_ptr;
	extern void* _addPackFromPackId__YAXPEAULambdaPack1__AEBUPackIdVersion___Z_ptr;
	extern void* _initializeResourceStack_VanillaGameModuleClient__QEAAXAEAVResourcePackRepository__AEAVResourcePackStack__AEBVBaseGameVersion___Z_ptr;
	extern void* _initializeResourceStack2_VanillaGameModuleClient__QEAAXAEAVResourcePackRepository__AEAVResourcePackStack__AEBVBaseGameVersion__W4ResourceLoadingPhase_GameModuleClient___Z_ptr;
	extern void* _registerButtonDownHandler_InputHandler__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__V_$function_$$A6AXW4FocusImpact__AEAVIClientInstance___Z_3__N_Z_ptr;
	extern void* _registerButtonUpHandler_InputHandler__QEAAXV_$basic_string_DU_$char_traits_D_std__V_$allocator_D_2__std__V_$function_$$A6AXW4FocusImpact__AEAVIClientInstance___Z_3__N_Z_ptr;
	extern void* __registerInputHandlers_MinecraftInputHandler__QEAAXXZ_ptr;
	extern void* _assignDefaultMapping_RemappingLayout__QEAAX$$QEAV_$vector_VKeymapping__V_$allocator_VKeymapping___std___std___Z_ptr;
	extern void* __populateKeyboardDefaults_VanillaClientInputMappingFactory__QEAAXAEAVRemappingLayout___Z_ptr;
	extern void* __populateGamepadDefaults_VanillaClientInputMappingFactory__QEAAXAEAVRemappingLayout___Z_ptr;
	extern void* __addFullKeyboardGamePlayControls_VanillaClientInputMappingFactory__QEAAXAEAVKeyboardInputMapping__AEAVMouseInputMapping___Z_ptr;
	extern void* __addInvariantGamePlayGameControllerControls_VanillaClientInputMappingFactory__QEAAXAEAVGameControllerInputMapping__W4MappingControllerType_ClientInputMappingFactory___Z_ptr;
	extern void* __handleDuplicates_ControlsSettingsScreenController__QEAAXAEAVRemappingLayout___Z_ptr;
}

void InitBedrockPointers();
void InitVersionPointers(std::string);
