name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
    - name: Checkout Common repo
      uses: actions/checkout@v2
      with:
        repository: MinecraftZenova/Common
        path: Common
    - name: Setup build directory
      run: |
        mkdir build
    - name: cmake
      working-directory: ./build
      run: cmake --build ../
    - name: tree
      run: tree ./build
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: ZenovaAPI
    #    path: ./build