name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
    - name: Checkout Common repo
      uses: actions/checkout@v2
      with:
        repository: MinecraftZenova/Common
        path: Common
    - name: Setup build directory
      run: mkdir build
    - name: cmake
      run: |
        cmake -S . -B build
        cmake --build build --config Release
    - name: Upload x64
      uses: actions/upload-artifact@v2
      with:
        name: ZenovaAPI.dll
        path: build/ZenovaAPI.dll