name: ZenovaAPI Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  # Todo: somehow remove the if master check (dunno if this is possible)
  build:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build.yml

  # There has to be a better way to do this
  rcedit:
    name: Rcedit
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Grab Rcedit
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "electron/rcedit"
          file: "rcedit-x86.exe"

      - name: Cache file
        uses: actions/cache@v3
        with:
          path: "rcedit-x86.exe"
          key: ${{ github.sha }}-rcedit

  deploy:
    name: Create Release
    if: github.ref == 'refs/heads/master'
    needs: [build, rcedit]
    runs-on: windows-latest
    
    steps:
      - name: Set Git Tag
        run: |
          if("${{ github.ref }}" -match "refs\/tags\/([0-9]+\.[0-9]+\.[0-9]+)")
          { echo ('ZA_TAG='+$matches.1) >> $env:GITHUB_ENV}

      - name: Grab all Artifacts 
        uses: actions/download-artifact@v3

      - name: Cache file
        uses: actions/cache@v3
        with:
          path: "rcedit-x86.exe"
          key: ${{ github.sha }}-rcedit

      - name: Update Version Resource
        if: env.ZA_TAG != null
        run: |
          .\rcedit-x86.exe ZenovaAPI.dll --set-file-version $env:ZA_TAG
        
      - name: Create Development Package
        uses: papeloto/action-zip@v1
        with:
          files: inc/ lib/
          dest: ZenovaAPI-dev.zip

      - name: Create Tagged Release
        if: env.ZA_TAG != null
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ZenovaAPI-dev.zip
            ZenovaAPI.dll