name: "tagged-release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Create tagged release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ZenovaAPI.dll